//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcStokDBEntities : DbContext
    {
        public MvcStokDBEntities()
            : base("name=MvcStokDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblKategoriler> TblKategoriler { get; set; }
        public virtual DbSet<TblMusteriler> TblMusteriler { get; set; }
        public virtual DbSet<TblPersoneller> TblPersoneller { get; set; }
        public virtual DbSet<TblSatislar> TblSatislar { get; set; }
        public virtual DbSet<TblUrunler> TblUrunler { get; set; }
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
    }
}
