//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSatislar
    {
        public int ID { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<int> PERSONEL { get; set; }
        public Nullable<int> MUSTERI { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    
        public virtual TblMusteriler TblMusteriler { get; set; }
        public virtual TblPersoneller TblPersoneller { get; set; }
        public virtual TblUrunler TblUrunler { get; set; }
    }
}
